### ISSUE TITLE
Moped::Errors ... failed with error "_a != -1"):

### ISSUE THREAD

**Issue by JohnBat26** [mongoid/moped#149]
Hi.
I get next error in process save entity in DB:

Moped::Errors::OperationFailure (The operation: #<Moped::Protocol::Command
  @length=92
  @request_id=849
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="web-collaboration-production.$cmd"
  @skip=0
  @limit=-1
  @selector={:getlasterror=>1, :safe=>true}
  @fields=nil>
failed with error "_a != -1"):

moped 1.4.2
mongoid 3.0.21

**Comment by shulmang** [comment]
FYI I was able to move past a case of Moped::Errors ... failed with error "_a != -1" on an old instance of Mongo 2.4.9 caused by a crash of mongod during building of indexes by doing mongodump & mongorestore --drop.  I suspect dropping and recreating indexes may have corrected this case also.
