### ISSUE TITLE
Rename collection method.

### ISSUE THREAD

**Issue by Exoth** [mongoid/moped#196]
Mongo Ruby driver has a very useful method of collection renaming, so with Mongoid 2 I could use this:

```
Mongoid.database.collection('foo').rename('bar')
```

But Moped doesn't seem to have anything like this, so I'm forced to use a custom helper like this:

```
def rename_collection(from, to)
  session = Mongoid.default_session
  database_name = session.options[:database]
  session.with(database: 'admin').command(renameCollection: "#{database_name}.#{from}", to: "#{database_name}.#{to}")
end
```

It would be great if Moped gets a simpler way of doing this.

**Comment by tetherit** [comment]
This seems to no longer work with Mongoid 5 :( -- Any suggestion how to rename a collection with Mongoid 5?
