### ISSUE TITLE
WiredTiger / MongoDB 3.0 Compatibility

### ISSUE THREAD

**Issue by dedene** [mongoid/moped#356]
MongoDB 3.0, combined with their new efficient WiredTiger storage engine, introduced some changes: http://docs.mongodb.org/manual/release-notes/3.0-compatibility/#compatibility-driver-versions

Currently, queries using Moped to `system.indexes` and `system.namespaces` (to query collection names and indexes) is returning nothing. 

Any idea where to start looking to fix this?

Or is the plan to leave Moped as-is and move to the official MongoDB 2.0 driver? mongoid/mongoid#3941

**Comment by dedene** [comment]
Or is the plan to leave Moped as-is and move to the official MongoDB 2.0 driver? https://github.com/mongoid/mongoid/pull/3941

**Comment by arthurnn** [comment]
The plan is to move back to MongoDB 2.0 official driver..
@durran is working on it.

**Comment by dedene** [comment]
Ok, thanks!!

**Comment by diziet** [comment]
@arthurnn -- is there somewhere we can subscribe to this switch to the MongoDB 2.0 driver? Really excited to try out wiredTiger

**Comment by arthurnn** [comment]
@diziet you can subscribe to PR #3941

**Comment by johnnyshields** [comment]
Does anyone have a monkey patch which adds support for indexes/collections methods from WiredTiger to Moped?

**Comment by johnnyshields** [comment]
Here's the monkey patch for Moped in case anyone is looking for it. Use at your own risk.

(edit: removed see next comment)

**Comment by johnnyshields** [comment]
Updated: full WiredTiger support for Mongoid 3/4 is here: https://github.com/johnnyshields/mongoid_monkey
