### ISSUE TITLE
Support SCRAM authenitcation method for MongoDB 3.0 users

### ISSUE THREAD

**Issue by troex** [mongoid/moped#367]
Currently it's not possible to authenticate for new users created in MongoDB 3.0 using default MONGODB-CR mechanism because it was discarded in favor of SCRAM-SHA-1. More info http://docs.mongodb.org/manual/release-notes/3.0-scram/

**Comment by lmancilla** [comment]
+1

**Comment by durran** [comment]
This will not be supported as Moped is EOL with the release of the official Ruby Driver 2.0. Mongoid 5 will migrate over to the official driver in the upcoming weeks and if you are simply using the driver directly I would recomment switching to the official driver.
