### ISSUE TITLE
duplicate objectids under puma server with multiple threads

### ISSUE THREAD

**Issue by apolzon** [mongoid/moped#372]
This is really an issue in the BSON gem, but it looks like issue reporting is disabled on that repo.

With the puma ruby server, it utilizes multiple threads under a single process. By default, each puma process can spawn up to 16 threads. If you make enough simultaneous create requests, you can get two objects with the same id which results in the data for the second one overwriting that of the first (two requests get picked up by the same process, ie puma worker, which have identical process ids, but different Thread.current object ids).

It looks like the generate method special-cases the jRuby scenario to include the Thread.current's object_id in the process_id. I'm not exactly sure what the best way to detect the puma case would be, but I didn't see this issue mentioned anywhere so at the very least, hopefully this saves someone a headache. Always including the thread's object id would work, but I imagine there is a reason the current code doesn't do that.

For now, I've updated my puma config to limit each puma process to a single thread, which feels like I'm not getting much out of puma anymore, but at least it averts the issue at hand.

**Comment by fabiob** [comment]
Are you sure it's possible to generate duplicate `BSON::ObjectId`s?

I've just checked the code, and looks like it uses a counter, protected by a `Mutex`, when generating the ID:

https://github.com/mongodb/bson-ruby/blob/84d8acd32ce9067ad646755e52f472a6ad685918/lib/bson/object_id.rb#L348

Do you have any other evidence for this claim?

**Comment by apolzon** [comment]
Hmm, I actually didn't see that method when I was looking at the source. Its definitely hard to reproduce, but I was seeing odd behavior in my app and was pretty sure it was being caused by multiple new documents being assigned the same database id. I'll have to do a little more investigating and see if I can put together a simple app for reproduction.

**Comment by fabiob** [comment]
If you are running inside docker containers, the code can be a little risky, since your process will always have PID=1. In that case, the `Socket.gethostname` would be the only source of entropy (aside from the timestamp, which we all know it's not enough).

**Comment by apolzon** [comment]
I just ran some more tests locally and I can't reproduce it anymore, so I'll close the issue.
