### ISSUE TITLE
support mongodb 3+ auth

### ISSUE THREAD

**Issue by khoan** [mongoid/moped#387]
it appears moped 2 cannot auth against mongoldb 3. Is there any plan to support mongodb 3 (would love to play around with wiredtiger)?

```
Moped::Errors::AuthenticationFailure: The operation: #<Moped::Protocol::Commands::Authenticate
  @length=153
  @request_id=2
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="issue_stage.$cmd"
  @skip=0
  @limit=-1
  @selector={:authenticate=>1, :user=>"bam", :nonce=>"968e420d86df0df1", :key=>"d318ff0844342a8ebdab70b45931e8931"}
  @fields=nil>
failed with error 18: "auth failed"
```

**Comment by durran** [comment]
Moped is EOL with Mongoid 5 so there is no plan to add it unless someone is to submit a pull request. If you are just using the driver directly I would recommend switching to the official Ruby driver 2.0.6 or 2.1.0.beta. The official driver is more stable, more feature complete, threadsafe, and offically supported. :)
